package com.farsitel.bazaar.common.model.cinema;

/* compiled from: ViewHolderItem.kt */
public enum CinemaViewItemType {
    CINEMA_INFO,
    VIDEO_ACTIONS,
    GENRE,
    DESCRIPTION,
    CREWS,
    CREW_ITEM,
    PAGE_ROW_VIDEO,
    OTHER_INFO_TITLE_ITEM,
    OTHER_INFO_ITEM,
    SCREEN_SHOT,
    REVIEW_TITLE,
    REVIEW_ITEM,
    REVIEW_ACTION,
    LOADING_ITEM,
    ADD_REVIEW,
    SERIES_SINGLE_SEASON_ITEM,
    SERIES_SEASON_ITEM,
    SERIES_SEASON_LIST__ITEM,
    RETRY_ITEM,
    SERIES_EPISODE_ITEM,
    SEASON_EPISODE_ITEM,
    SERIES_EPISODE_SEE_MORE_ITEM,
    DIVIDER,
    EPISODE_DETAIL_INFO,
    EPISODE_DETAIL_ACTIONS,
    EPISODE_DETAIL_DESCRIPTION,
    EPISODE_DETAIL_EPISODES,
    EPISODE_DETAIL_EPISODE_ITEM
}
